package activities.inApp.ernaehrungTab;

import android.content.Context;
import android.view.LayoutInflater;
import android.view.View;
import android.widget.FrameLayout;
import android.widget.LinearLayout;
import android.widget.TextView;

import static activities.generic.DateTimeHelper.getMonday;
import static activities.generic.ViewHelper.roundedBg;
import static activities.generic.ViewHelper.FAB_CORNER_RADIUS_DP;

import androidx.core.content.ContextCompat;

import java.time.LocalDate;

import com.autosecretary.R;

import activities.generic.ViewBuilder;
import controller.MealManager;
import controller.MealManager.MealListener;

public class MealPlanView implements MealListener, ViewBuilder {

    private final Context context;
    private final MealManager manager;

    // UI
    private View root;
    private LinearLayout foodGroupContainer;
    private FrameLayout mealContent;
    private TextView tabWeekPlan;
    private TextView tabRecipes;
    private TextView tabShopping;
    private TextView tabPantry;
    private FrameLayout fabAdd;

    private int currentTab = 0;
    private LocalDate currentWeekStart;

    // Sub-Komponenten
    private FoodGroupHeader headerInstance;
    private WeekPlanTab weekPlanInstance;
    private RecipesTab recipesInstance;
    private ShoppingTab shoppingInstance;
    private PantryTab pantryInstance;

    public MealPlanView(Context context, MealManager manager) {
        this.context = context;
        this.manager = manager;
        this.manager.setListener(this);
        this.currentWeekStart = getMonday(LocalDate.now());
    }

    @Override
    public View buildView() {
        root = LayoutInflater.from(context).inflate(R.layout.view_meal_plan, null);

        // Bind Views
        foodGroupContainer = root.findViewById(R.id.food_group_container);
        mealContent = root.findViewById(R.id.meal_content);
        tabWeekPlan = root.findViewById(R.id.tab_week_plan);
        tabRecipes = root.findViewById(R.id.tab_recipes);
        tabShopping = root.findViewById(R.id.tab_shopping);
        tabPantry = root.findViewById(R.id.tab_pantry);
        fabAdd = root.findViewById(R.id.fab_add);

        // Sub-Tab-Listener
        tabWeekPlan.setOnClickListener(v -> selectSubTab(0));
        tabRecipes.setOnClickListener(v -> selectSubTab(1));
        tabShopping.setOnClickListener(v -> selectSubTab(2));
        tabPantry.setOnClickListener(v -> selectSubTab(3));

        // Sub-Komponenten erstellen
        headerInstance = new FoodGroupHeader(context, manager);

        FrameLayout rootContainer = (FrameLayout) root;

        weekPlanInstance = new WeekPlanTab(context, manager);
        weekPlanInstance.setListener(this::render);
        weekPlanInstance.initModals(rootContainer);

        recipesInstance = new RecipesTab(context, manager);
        recipesInstance.setListener(this::render);
        recipesInstance.initModals(rootContainer);

        shoppingInstance = new ShoppingTab(context, manager);
        shoppingInstance.setListener(this::render);

        pantryInstance = new PantryTab(context, manager);
        pantryInstance.setListener(this::render);
        pantryInstance.initModals(rootContainer);

        // FAB
        fabAdd.setBackground(roundedBg(context,
            ContextCompat.getColor(context, R.color.accent), FAB_CORNER_RADIUS_DP));
        fabAdd.setOnClickListener(v -> {
            switch (currentTab) {
                case 0 -> weekPlanInstance.showAutoGenerateDialog();
                case 1 -> recipesInstance.openCreateModal();
                case 3 -> pantryInstance.showPantryModal(null);
            }
        });

        // Initial
        render();
        selectSubTab(0);

        return root;
    }

    @Override
    public void onDataUpdated() {
        if (root != null) {
            root.post(this::render);
        }
    }

    private void selectSubTab(int index) {
        currentTab = index;

        int accent = ContextCompat.getColor(context, R.color.accent);
        int secondary = ContextCompat.getColor(context, R.color.text_secondary);

        tabWeekPlan.setTextColor(index == 0 ? accent : secondary);
        tabRecipes.setTextColor(index == 1 ? accent : secondary);
        tabShopping.setTextColor(index == 2 ? accent : secondary);
        tabPantry.setTextColor(index == 3 ? accent : secondary);

        // FAB nur bei Wochenplan (0), Rezepte (1) und Vorrat (3)
        fabAdd.setVisibility(
            (index == 0 || index == 1 || index == 3) ? View.VISIBLE : View.GONE);

        renderContent();
    }

    private void navigateWeek(int delta) {
        currentWeekStart = currentWeekStart.plusWeeks(delta);
        render();
    }

    private void render() {
        headerInstance.render(foodGroupContainer);
        renderContent();
    }

    private void renderContent() {
        Runnable onPrev = () -> navigateWeek(-1);
        Runnable onNext = () -> navigateWeek(1);
        switch (currentTab) {
            case 0 -> weekPlanInstance.render(mealContent, currentWeekStart, onPrev, onNext);
            case 1 -> recipesInstance.render(mealContent);
            case 2 -> shoppingInstance.render(mealContent, currentWeekStart, onPrev, onNext);
            case 3 -> pantryInstance.render(mealContent);
        }
    }
}
