package com.aisecretary.taskmaster;

/**
 * Resource IDs - Auto-generated class
 *
 * This file would normally be generated by aapt2, but is created manually
 * for development purposes in Termux.
 *
 * In a full build, this file is regenerated automatically.
 */
public final class R {

    public static final class id {
        public static final int task_list_container = 0x7f010001;
        public static final int stats_text = 0x7f010002;
        public static final int add_task_button = 0x7f010003;
        public static final int header_title = 0x7f010004;
        public static final int streak_text = 0x7f010005;
    }

    public static final class layout {
        public static final int activity_main = 0x7f020001;
    }

    public static final class string {
        public static final int app_name = 0x7f030001;
        public static final int taskmaster_title = 0x7f030002;
        public static final int task_new = 0x7f030003;
        public static final int task_title_hint = 0x7f030004;
        public static final int task_description_hint = 0x7f030005;
        public static final int task_priority = 0x7f030006;
        public static final int task_complete = 0x7f030007;
        public static final int task_delete = 0x7f030008;
        public static final int stats_today = 0x7f030009;
        public static final int stats_week = 0x7f03000a;
        public static final int stats_average = 0x7f03000b;
        public static final int stats_streak = 0x7f03000c;
        public static final int widget_next_task = 0x7f03000d;
        public static final int widget_no_tasks = 0x7f03000e;
    }

    public static final class color {
        public static final int colorPrimary = 0x7f040001;
        public static final int colorPrimaryDark = 0x7f040002;
        public static final int colorAccent = 0x7f040003;
        public static final int backgroundColor = 0x7f040004;
        public static final int backgroundDark = 0x7f040005;
        public static final int textPrimary = 0x7f040006;
        public static final int textSecondary = 0x7f040007;
        public static final int textOnPrimary = 0x7f040008;
        public static final int statusOverdue = 0x7f040009;
        public static final int statusCompleted = 0x7f04000a;
        public static final int statusPending = 0x7f04000b;
        public static final int priorityHigh = 0x7f04000c;
        public static final int priorityMedium = 0x7f04000d;
        public static final int priorityLow = 0x7f04000e;
    }

    public static final class mipmap {
        public static final int ic_launcher = 0x7f050001;
    }
}
