package com.autosecretary.features.task.data;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import androidx.room.Entity;
import androidx.room.PrimaryKey;
import androidx.room.Embedded;
import androidx.room.ForeignKey;
import androidx.room.Ignore;
import androidx.room.Index;
import androidx.annotation.NonNull;

/**
 * Room entity for scheduled/completed time blocks. Each slot belongs to one task
 * via {@code taskId}. Tracks planned (start/end) and actual (realStart/realEnd)
 * execution times.
 *
 * <p><strong>Slot lifecycle:</strong>
 * <ol>
 *   <li>Scheduler generates the slot and sets {@code scheduled=true}, {@code day}, {@code start}, {@code end}.</li>
 *   <li>User taps once → {@code realStart} is recorded (slot is STARTED, shown with green background).</li>
 *   <li>User taps again → {@code realEnd} is recorded and {@code completed=true} (slot is DONE).</li>
 * </ol>
 *
 * <p><strong>Two kinds of hierarchy:</strong>
 * <ul>
 *   <li><em>Task hierarchy</em> — parent-child <em>tasks</em> linked via {@code TaskRelation} (separate table).</li>
 *   <li><em>Slot hierarchy</em> — when a parent task's slot is scheduled, child-task slots are
 *       nested inside the parent's time block. Each child slot's {@link #parent} points to the
 *       containing parent-task slot. Used for cascade eviction and UI tree rendering.
 *       See also {@link #chainId} for prerequisite-chain grouping (separate concept).</li>
 * </ul>
 */
@Entity(tableName = "task_slots",
    indices = @Index("taskId"),
    foreignKeys = @ForeignKey(
        entity = TaskCore.class,
        parentColumns = "id",
        childColumns = "taskId",
        onDelete = ForeignKey.CASCADE
    ))

public class TaskSlot {

    /**
     * How a group of related slots participates in the competitive displacement algorithm.
     * <ul>
     *   <li>{@code CHAIN} — a set of slots representing a prerequisite chain (A → B → C)
     *       that must be placed or displaced atomically; evicting one evicts all in the chain.</li>
     *   <li>{@code FIXED} — a fixed-time (TERMIN) block that cannot be displaced by the scheduler.</li>
     *   <li>{@code SINGLE} — an independent slot with no chain grouping; can be displaced individually.</li>
     * </ul>
     */
    public enum DisplacementGroupType {
        CHAIN, FIXED, SINGLE
    }

    @PrimaryKey() @NonNull
    public String id = UUID.randomUUID().toString();
    public String taskId;
    /**
     * Slot-level parent ID for child-task containment. When a parent task is scheduled,
     * its child tasks' slots are placed within the parent's time block; each child slot's
     * {@code parent} points to the containing parent-task slot ID. Distinct from the
     * task-level parent-child relationship (which lives in {@code TaskRelation}).
     * Used by {@code removeOrphanedChildSlots} for cascade eviction when the parent
     * slot is displaced. The in-memory {@link #children} list mirrors this linkage
     * for tree traversal.
     */
    public String parent;
    /**
     * ID shared by all slots belonging to the same prerequisite chain. Used during re-scheduling
     * to evict or preserve the entire chain atomically (all-or-nothing displacement).
     */
    public String chainId;
    /** In-memory slot tree for chain traversal during scheduling. Not persisted ({@code @Ignore}). */
    @Ignore
    public List<TaskSlot> children = new ArrayList<>();

    public LocalDate day;
    /** Planned start time (set by the scheduler). May differ from {@link #realStart}. */
    public LocalTime start;
    /** Planned end time (set by the scheduler). May differ from {@link #realEnd}. */
    public LocalTime end;
    /**
     * True when this slot was generated by the scheduler and included in the active planning
     * window. False for orphaned or manually created slots. A slot can be {@code scheduled=true}
     * but not yet started ({@code realStart == null}) or completed.
     */
    public boolean scheduled;
    /** True when the user completed the second check-off tap ({@code realEnd} recorded). */
    public boolean completed;
    /**
     * Numeric score assigned by {@code TaskScorer} during scheduling; higher is better.
     * Persisted so it can serve as a displacement loss baseline on re-planning without
     * re-running the full scoring algorithm. See {@link #displacementScore}.
     */
    public int score;
    /**
     * Persisted displacement value used as reproducible loss baseline during re-planning.
     */
    public int displacementScore;
    /**
     * Atomic displacement group id (e.g. prerequisite chain or fixed block group).
     */
    public String displacementGroupId;
    /**
     * Group type for displacement semantics.
     */
    public DisplacementGroupType displacementGroupType;

    /** Actual start time recorded on first check-off tap (null until the user starts). */
    public LocalTime realStart;
    /** Actual end time recorded on second check-off tap (null until the user completes). */
    public LocalTime realEnd;
}
